Algoritmo "primeiro_codigo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Guanabara
// Descrição   : Escrever na tela "Olá, mundo!"
// Autor(a)    : Roberto Rocha
// Data atual  : 13/09/2022
Var
// Seção de Declarações das variáveis

   msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   msg <- "Olá, Mundo!"
   Escreval(msg)

Fimalgoritmo